### PR TITLE
dracut fixes for iscsiroot

### PR DESCRIPTION
**Pull request by mwilck**
References: bsc#1121238, bsc#1130107, bsc#1130114
The last 5 patches are mostly minor cleanups, please consider anyway.

### CODE REVIEW

**Review by gonzoleeman — COMMENTED** [review]
Shouldn't that be "if [ "$netif" != "timeout" ] ; then"?

**Review by gonzoleeman — APPROVED** [review]

**Review by gonzoleeman — APPROVED** [review]

**Comment by mwilck** [comment]
> Shouldn't that be "if [ "$netif" != "timeout" ] ; then"?

Not sure what you mean ... in the loop, where we run "iscsiadm --login", I have `if [ "$netif" != "timeout" ]`. Outside the loop (line 250), I handle the timeout case, so `if [ "$netif" = "timeout" ]` is correct there. No?

**Review by gonzoleeman — APPROVED** [review]

**Review by gonzoleeman — APPROVED** [review]

**Comment by danimo** [comment]
Could you rebase this patchset by rebasing them on the upstream patches in master? This way, they can go straight to upstream, and we can backport the whole module including all upstream fixes.

Background: I have submitted this module to upstream, and this way we can keep them from diverging again. Also, I would like to avoid diverging from upstream if possible. This way, we'll soon be able to catch up.

**Comment by mwilck** [comment]
@danimo, I need a "dracut upstream"  code base that works with SLE (or at least TW) for testing. Can you point me to a suitable git branch / OBS package, please?

**Comment by danimo** [comment]
Obsoleted by patch set from master which has now landed in the SUSE/044 and SUSE/049 branches.

**Pull request closed without merging**
