### PR TITLE
iscsi / NFS: fixes for static IP address configuration

### PR DESCRIPTION
**Pull request by mwilck**
Pending review, for bsc#1167494.

### CODE REVIEW

**Comment by tblume** [comment]
Looks good to me. The only nitpick I've found, you might want to use the strglobin library function to determine ipv6 addresses and brackets, since this is done elsewhere in the code, e.g.:

if strglobin $iscsi_target_ip '*:*:*' && ! strglobin $iscsi_target_ip '['; then

Have you got a repo ready that I could use for testing?

**Comment by mwilck** [comment]
> if strglobin $iscsi_target_ip '_:_:*' && ! strglobin $iscsi_target_ip '['; then

IIUC `module-setup.sh` is run under bash, so using the the bashism `[[ $ip = *:* ]]` should be ok. The idea to check whether "`[`" was already in the string makes sense. I will double check.

> Have you got a repo ready that I could use for testing?

Not yet, sorry. I just applied the patches in place. Btw I have no NFS installation I could test with, only iSCSI. So if you could cover NFS, I'd be highly grateful.

**Comment by tblume** [comment]
> IIUC `module-setup.sh` is run under bash, so using the the bashism `[[ $ip = *:* ]]` should be ok. The idea to check whether "`[`" was already in the string makes sense. I will double check.

ok
 
> > Have you got a repo ready that I could use for testing?
> 
> Not yet, sorry. I just applied the patches in place. Btw I have no NFS installation I could test with, only iSCSI. So if you could cover NFS, I'd be highly grateful.

np, I can test this.

**Comment by mwilck** [comment]
Changed code to use `strglob()`.

**Comment by mwilck** [comment]
Upstream PR: https://github.com/dracutdevs/dracut/pull/857

**Pull request merged**
