### PR TITLE
Fix test in lsinitrd

### PR DESCRIPTION
**Pull request by Vogtinator**
Cherry-pick of https://github.com/dracutdevs/dracut/pull/809.

Fixes https://progress.opensuse.org/issues/65334

### CODE REVIEW

**Comment by danimo** [comment]
Good catch. Thanks.

**Comment by danimo** [comment]
Upstream PR: https://github.com/dracutdevs/dracut/pull/810

**Comment by Vogtinator** [comment]
> Upstream PR: [dracutdevs/dracut#810](https://github.com/dracutdevs/dracut/pull/810)

Thanks, but as I wrote in the PR description, I already opened dracutdevs/dracut#809...

**Comment by danimo** [comment]
Yepp, noticed :) Approving now.

**Pull request merged**
